conversation/urls.py
from django.urls import path

from . import views


app_name = 'conversation'
urlpatterns = [
    path('', view=views.inbox, name='inbox'),
    path('<int:pk>/conversation/', view=views.detail, name='detail'),
    path('new/<int:item_pk>/', view=views.new_conversation, name='new')
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path


from . import views
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
] 

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

marketplaceapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('core/', include('core.urls')),
    path('items/', include('items.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models
from django.contrib.auth.models import User



class Category(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(blank=True, null=True)


    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return (self.name).capitalize()


class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE) 
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return (self.name).capitalize()

    

items/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description','price','image') 
        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'category': forms.Select(attrs={'class': INPUT_CLASSES}),
            'description': forms.Textarea(attrs={'class': INPUT_CLASSES}),
            'price': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'image': forms.FileInput(attrs={'class': INPUT_CLASSES}),
        }


class UpdateItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','description','price','image','is_sold') 
        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'description': forms.Textarea(attrs={'class': INPUT_CLASSES}),
            'price': forms.NumberInput(attrs={'class': INPUT_CLASSES}),
            'image': forms.FileInput(attrs={'class': INPUT_CLASSES}),
        }

items/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from .forms import NewItemForm, UpdateItemForm
from .models import Item, Category



def items(request):
    items = Item.objects.filter(is_sold=False)
    query = request.GET.get('query','')
    category_id = request.GET.get('category',0)
    categories = Category.objects.all()

    if query:
        items = Item.objects.filter(Q(name__icontains=query)|Q(description__icontains=query))

    if category_id:
        items = Item.objects.filter(category_id=category_id)

    context = {'query':query, 'items': items, 'categories': categories, 'category_id': int(category_id)}
    return render(request, 'items/items.html', context)


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[:3]
    context = {'item': item, 'related_items': related_items}
    return render(request, 'items/detail.html', context)


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid: 
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('items:detail', pk=item.id)
    else:  form = NewItemForm()
    context = {'form': form, 'title': 'New Item'}
    return render(request, 'items/form.html', context)

@login_required
def update(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = UpdateItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid: 
            form.save()

            return redirect('items:detail', pk=item.id)
    else:  form = UpdateItemForm(instance=item)
    context = {'form': form, 'title': 'Update Item'}
    return render(request, 'items/form.html', context)

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

items/templates/items/detail.html
{% extends 'core/base.html' %}


{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6 ">
        <div class="col-span-3">
            <img src="{{ item.image.url}}" alt="{{ item.name }}" class="rounded-xl">
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h2 class="text-2xl">{{item.name}}</h2>
            <p class="text-gray-500"> <strong>Price</strong>: GHS {{ item.price|floatformat:"2" }}</p>
            <p class="text-gray-500 text-sm"> <strong>Seller:</strong> {{ item.created_by.username }}</p>

            {% if item.description %}
                <p class="text-gray-700 text-sm"> <strong class="text-gray-700">Descritpion:</strong> <br> {{ item.description }}</p>
            {% endif %}

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>Your product</p>
                    <a href="{% url 'items:update' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Update</a>
                    <a href="{% url 'items:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Delete</a>
                </div>
            {% else %}
                <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
            {% endif %}

        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for related_item in related_items %}
            <div>
                <a href="{% url 'items:detail' related_item.id %}">
                    <div>
                        <img src="{{ related_item.image.url }}" alt="{{ related_item.name }}" class="rounded-t-xl object-contain h-48 w-100">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ related_item.name }}</h2>
                    </div>
                </a>

            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

items/templates/items/form.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}


{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ title }}</h1>

        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}

            <div class="space-y-4">
                {{ form.as_p }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for error in form.errors %}
                        {{ field.errors }}
                    {% endfor %}
                </div>

                {{ form.non_field_errors }}
            {% endif %}
            <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

items/templates/items/items.html
{% extends 'core/base.html' %}

{% block title %} Items {% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form action="." method="{% url 'items:items' %}">
                <input name="query" placeholder="Try typing chair, TV, or shirt" type="text" value="{{ query }}" class="w-full px-6 py-4 border rounded-xl">
                <button class="mt-2 px-8 py-4 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>
            
            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}" >
                        <a href="{% url 'items:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul class="font-semibold">
                <li><a href="{% url 'items:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 rounded-xl text-white">Clear</a></li>
            </ul>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3 ">
                {% for item in items %}
                <div>
                    <a href="{% url 'items:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-xl object-contain h-48 w-100">
                        </div>
    
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: GHS {{ item.price|floatformat:"2" }}</p>
                            <p class="text-gray-500 text-sm"> Descritpion: <br> {{ item.description }}</p>
                        </div>
                    </a>
    
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    
{% endblock %}